### ISSUE TITLE
blink boots

### ISSUE THREAD

**Issue by KoViDm** [MrDimaseS/Ebf-BugReports#93] opened 2023-05-08 19:42 UTC
Sometimes boots teleport to another place (not where the cursor is)

![image](https://user-images.githubusercontent.com/132946572/236917350-7d9e2d8e-7b74-4323-94de-bc8570c13234.png)

**Comment by Yahnich** [comment] 2023-05-08 19:44
duplicate of #69

**Closed by Yahnich** 2023-05-08 19:44 UTC
